config/routes.rb
Rails.application.routes.draw do
  get "/about", to: "about#index"
  get "/friends", to: "friends#index"
  resources :spots
  resources :users
  resources :sessions
  resources :friends
  resources :memberships
  root "sessions#index"

  #  delete "/friends/:id", to: "friends#destroy"
  # post "friends", to: "friends#create"

  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "login", to: "user_sessions#new"
end

app/models/spot.rb
class Spot < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :sessions
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_spot, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create update destroy ], :if => Proc.new {|c| c.request.format.html?}

  # GET /spots or /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1 or /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots or /spots.json
  def create
    if Spot.exists?(name: spot_params["name"])
      @spot = Spot.find_by_name(spot_params["name"])
      respond_to do |format|
        format.html { redirect_to spot_url(@spot), notice: "Spot already exists." }
        format.json { render :show, status: :no_content, location: @spot }
      end
      return
    end

    @spot = Spot.new(spot_params)
    respond_to do |format|
      if @spot.save
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully created." }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1 or /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully updated." }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end
  ''
  # DELETE /spots/1 or /spots/1.json
  def destroy
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url, notice: "Spot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_spot
    @spot = Spot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def spot_params
    params.require(:spot).permit(:name)
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_with(model: spot) do |form| %>
  <% if spot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
        <% spot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spots/_spot.html.erb
<div id="<%= dom_id spot %>">
  <p>
    <strong>Name:</strong>
    <%= spot.name %>
  </p>
</div>

app/views/spots/edit.html.erb
<%= render "form", spot: @spot %>

app/views/spots/index.html.erb
<div id="spots">
  <% @spots.each do |spot| %>
    <p>
      <strong>
        <%= link_to spot.name, spot %>
      </strong><br>
      Created: <%= time_tag spot.created_at, "data-local": "time-ago"%>
    </p>
  <% end %>
</div>

app/views/spots/new.html.erb
<%= render "form", spot: @spot %>

app/views/spots/show.html.erb
<%= render @spot %>
<% if user_signed_in? %>
  <div>
    <%= link_to "Edit", edit_spot_path(@spot) %> |
    <%= link_to "Delete", spot_path(@spot), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </div>
<% end %>