config/routes.rb
Rails.application.routes.draw do
  get "/about", to: "about#index"
  get "/friends", to: "friends#index"
  resources :spots
  resources :users
  resources :sessions
  resources :friends
  resources :memberships
  root "sessions#index"

  #  delete "/friends/:id", to: "friends#destroy"
  # post "friends", to: "friends#create"

  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "login", to: "user_sessions#new"
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!

  def index
    @friendships = current_user.friendships.order(created_at: :desc)
    @users = User.where.not(id: (@friendships.map { |f| f.friend.id } << current_user.id)).order(:name)
  end

  def create
    Friendship.create!(user: current_user, friend: User.find(params[:id]))
    redirect_to friends_url
  end

  def destroy
    friendship = Friendship.find(params[:id])
    friendship.destroy
    redirect_to friends_url
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class="flex-container">
  <div class="flex-item">
    <h4><mark>Friends</mark></h4>
    <% @friendships.each do |friendship| %>
      <div class="flex-container">
        <div class="flex-item">
          <strong><%= friendship.friend.name %></strong>
        </div>
        <div class="flex-item">
          <%= link_to "Uninvite", friend_path(friendship), data: { turbo_method: :delete } %>
        </div>
      </div>
    <% end %>
    </p>
  </div>
  <div class="flex-item">
    <h4><mark>Not yet Friends</mark></h4>
    <% @users.each do |user| %>
      <div class="flex-container">
        <div class="flex-item">
          <strong><%= user.name %></strong>
        </div>
        <div class="flex-item">
          <%= link_to "Invite", friends_path(id: user.id), data: { turbo_method: :post } %>
        </div>
      </div>
    <% end %>
  </div>
</div>