config/routes.rb
Rails.application.routes.draw do
  get "/about", to: "about#index"
  get "/friends", to: "friends#index"
  resources :spots
  resources :users
  resources :sessions
  resources :friends
  resources :memberships
  root "sessions#index"

  #  delete "/friends/:id", to: "friends#destroy"
  # post "friends", to: "friends#create"

  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "login", to: "user_sessions#new"
end

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wingbuddies</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  <%= javascript_importmap_tags %>
</head>
<body>
<header>
  <h1>Wingbuddies</h1>
  <nav>
    <%= link_to "Sessions", sessions_path %>
    <%= link_to "Spots", spots_path %>
    <%= link_to "About", about_path %>
    <% if user_signed_in? %>
      <%= link_to "Logout", logout_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to "Login", login_path %>
    <% end %>
  </nav>
</header>
<main>
  <%= yield %>
</main>
<footer>
  <p>Wingbuddies.de by Ralf Wirdemann</p>
</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wingbuddies</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  <%= javascript_importmap_tags %>
</head>
<body>
<header>
  <h1>Wingbuddies</h1>
  <nav>
    <% if user_signed_in? %>
      <%= link_to "Sessions", sessions_path %>
      <%= link_to "Friends", friends_path, class: "navbar-item" %>
      <%= link_to "#{current_user.name.humanize}'s Profile", users_path, class: "navbar-item" %>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to "Logout", logout_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to "Sessions", sessions_path %>
      <%= link_to "Login", login_path %>
    <% end %>
  </nav>
</header>
<main>
  <%= yield %>
</main>
<footer>
  <p>
    Wingbuddies was created by
    <a href="https://ralfwirdemann.de">Ralf Wirdemann</a>
  </p>
</footer>
</body>
</html>